### ISSUE TITLE
Remove scrolling bars Deposit/Connect Wallet page

### ISSUE THREAD

**Issue by adam-bro** [Loopring/loopring-web-v2#574]
![unknown](https://user-images.githubusercontent.com/84410897/177686219-a631b631-0382-42b9-8034-374c5333a4a1.png)
![image01](https://user-images.githubusercontent.com/84410897/177686234-cfc9feb5-e066-4de8-9b13-2d546f59ba1c.jpg)

**Comment by windatang** [comment]
for MAC chrome without outside hardware mouth, it not display the scroll bar, otherwise it follow the default rule for display the bar, for good set at view, we want functionally working is more important... so will not fix the default style, make sure all device can worked well, will ignore the view
